### ISSUE TITLE
[bug]: /bin/sh: line 0: cd: OLDPWD not set

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#1523]
**Describe the bug**
In a forked copy of PWA Studio that worked for several months of daily dev, suddenly it can't build. Running `yarn run build` terminates with this error:

```
yarn run v1.15.2
$ yarn workspace @watscomagento/ce run watch; cd - >/dev/null
$ webpack-dev-server --progress --color --env.mode development
Using environment variables from .env
TypeError: Cannot read property 'type' of undefined
    at Parser.match (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:67:22)
    at Parser.parseDirective (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:43:19)
    at Parser.parse (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:29:14)
    at module.exports (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:168:58)
    at comments.reduce (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/index.js:12:38)
    at Array.reduce (<anonymous>)
    at parseDirectives (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/index.js:11:40)
    at Promise.all.rootComponentFiles.map (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/pwa-buildpack/dist/WebpackTools/plugins/makeMagentoRootComponentsPlugin/index.js:75:13)
/bin/sh: line 0: cd: OLDPWD not set
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. `yarn run build`

**Expected behavior**
Server should build and start.

**Additional context**
I cloned the same repo into a new folder, installed dependencies, added the same `.env`, and the build works.

I used Kaleidoscope to compare every file between the two repos, and the only differences were in `node_modules`:

- brotli-size
- node-gyp
- node-zopfli-es

I tried deleting `node_modules` in the original repo and running `yarn install` but the issue persisted.

No idea what that error relates to.

**Possible solutions**

Re-cloning my whole repo resolved it. Just curious what the real cause was.

If I had to guess it's something with DEVCERT because of the error mentioning `OLDPWD not set` and I think DEVCERT is the only part of pwa-buildpack that needs the password.

Previously I have had issues with the certificate expiring, and documented that here:
https://manuals.gravitydept.com/frameworks/magento-pwa-studio/troubleshooting

Doing that had no effect here.

**Please complete the following device information:**
 - NPM version `npm -v`: 6.9.0
 - Node Version `node -v`: 10.15.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
Fixed in #1498 by removing the CD commands
