### ISSUE TITLE
[bug]: Venia storefront not accessible on cloud starter. Cause PR #1498

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1614]
**Describe the bug**
On accessing venia on storefront getting exception.
Build on commit  - 4db08e08  #1498

**To Reproduce**
1. Deploy build on commit 4db08e08 to cloud env.
2. Access venia storefront. Check with @dpatil-magento for the env to reproduce.

**Expected behavior**
Venia home page should load.

**Actual**
Fatal error: Uncaught TypeError: file_get_contents() expects parameter 1 to be a valid path, bool given in /app/vendor/magento/upward/src/Resolver/File.php:94 Stack trace: #0 /app/vendor/magento/upward/src/Resolver/File.php(94): file_get_contents(false) #1 /app/vendor/magento/upward/src/DefinitionIterator.php(208): Magento\Upward\Resolver\File->resolve('./asset-manifes...') #2 /app/vendor/magento/upward/src/DefinitionIterator.php(186): Magento\Upward\DefinitionIterator->getFromResolver('assetManifest', './asset-manifes...', Object(Magento\Upward\Resolver\File)) #3 /app/vendor/magento/upward/src/DefinitionIterator.php(99): Magento\Upward\DefinitionIterator->getFromDefinedValue('assetManifest', './asset-manifes...') #4 /app/vendor/magento/upward/src/Resolver/Template.php(60): Magento\Upward\DefinitionIterator->get('assetManifest') #5 /app/vendor/magento/upward/src/DefinitionIterator.php(208): Magento\Upward\Resolver\Template->resolve(Object(Magento\Upward\Definition)) #6 /app/vendor/magento/upward/src/DefinitionIterator.php in /app/vendor/magento/upward/src/Resolver/File.php on line 94

**Additional context**
1. This is broken as part of #1498.  Confirmed by deploying #1522  which got merged before #1498.
2. If we revert below changes of `upward.yml` file then storefront works fine but might break something on upward-js side. 
   `assetManifest: ./asset-manifest.json` to `assetManifest: ./dist/asset-manifest.json`
  bundles `inline: '.'` to     `inline: './dist'`
`inline: './static'` to `inline: './dist/static'`
`veniaTemplateIncludes: './templates'`  to `veniaTemplateIncludes: './dist/templates'`

**Comment by dpatil-magento** [comment]
We need to pass upward.yml file path of dist folder.
