### ISSUE TITLE
webpack issue when yarn run build

### ISSUE THREAD

**Issue by senioritydev** [magento/pwa-studio#2361]
I'm getting following error while building the app
As done few modifications in the category root component 

error
`ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
    Module build failed (from (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js):
    TypeError: Cannot read property 'type' of undefined
        at Parser.match (/var/www/html/PWA/node_modules/@magento/directive-parser/src/Parser.js:67:22)
        at Parser.parseDirective (/var/www/html/PWA/node_modules/@magento/directive-parser/src/Parser.js:43:19)
        at Parser.parse (/var/www/html/PWA/node_modules/@magento/directive-parser/src/Parser.js:29:14)
        at module.exports (/var/www/html/PWA/node_modules/@magento/directive-parser/src/Parser.js:168:58)
        at comments.reduce (/var/www/html/PWA/node_modules/@magento/directive-parser/src/index.js:12:38)
        at Array.reduce (<anonymous>)
        at parseDirectives (/var/www/html/PWA/node_modules/@magento/directive-parser/src/index.js:11:40)
        at Promise.all.rootComponentFiles.map (/var/www/html/PWA/packages/pwa-buildpack/lib/WebpackTools/plugins/RootComponentsPlugin.js:108:56)
        at process._tickCallback (internal/process/next_tick.js:68:7)
     @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js client[0]
`

**Comment by larsroettig** [comment]
Not reproducible pls add more details
