### ISSUE TITLE
[bug]: React Refresh is not working with webpack mode dev

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2689]
**Describe the bug**
React refresh is throwing error.

**To reproduce**
1. with latest develop branch
2. Run `webpack --no-progress --env.mode development`
3. Note error 
```
Error: [React Refresh] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.
```

**Expected behavior**
no error

**Additional context**
Same as reported here https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/169

**Possible solutions**
possible fix is to change 
node_modules/@magento/pwa-buildpack/lib/WebpackTools/configureWebpack/getClientConfig.js
```
            new ReactRefreshWebpackPlugin()
```
to
```
            new webpack.HotModuleReplacementPlugin(),
            new ReactRefreshWebpackPlugin()
```

However it might be better to move the above completely into the development section? Or am I missing something here?

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Linked to internal JIRA PWA-919

**Comment by NandiniJivainfotech123** [comment]
@magento I am working on this

**Comment by NandiniJivainfotech123** [comment]
I executed the steps which you have provided I didn't find any issue,

1.with latest develop branch
2.Run webpack --no-progress --env.mode development
3.Note error

![reference](https://user-images.githubusercontent.com/70904231/93356717-271bc600-f85d-11ea-87d9-a68ab29d57c1.PNG)

**Comment by sirugh** [comment]
@fooman are there other steps? Is this from the repo or from a scaffolded app?

**Comment by fooman** [comment]
Indeed this was with the scaffolded app. The command is taken from
https://github.com/magento/pwa-studio/blob/develop/packages/venia-concept/package.json#L16


```
git clone git@github.com:magento/pwa-studio.git
cd pwa-studio
DEBUG_PROJECT_CREATION=true ../pwa-studio/packages/pwa-buildpack/bin/buildpack create-project scaffold-test-1 --template "venia-concept" --name "scaffold-test-1" --author "test123 test@example.com" --backend-url "" --braintree-token "" --npm-client "yarn"
cd scaffold-test-1
yarn install (probably not needed)
./node_modules/webpack-cli/bin/cli.js --no-progress --env.mode development
```

![image](https://user-images.githubusercontent.com/455508/93410366-fc794e00-f8ec-11ea-980d-da7e2f6d4a00.png)


To note both 
`./node_modules/webpack-cli/bin/cli.js --no-progress --env.mode production` and 
`./node_modules/.bin/webpack-dev-server --progress --color --env.mode development` compile successfully.

**Comment by NandiniJivainfotech123** [comment]
@fooman ,i executed the below steps, I didn't find any issue.
git clone git@github.com:magento/pwa-studio.git
cd pwa-studio
DEBUG_PROJECT_CREATION=true ../pwa-studio/packages/pwa-buildpack/bin/buildpack create-project scaffold-test-1 --template "venia-concept" --name "scaffold-test-1" --author "test123 test@example.com" --backend-url "" --braintree-token "" --npm-client "yarn"
cd scaffold-test-1
yarn install (probably not needed)
./node_modules/webpack-cli/bin/cli.js --no-progress --env.mode development
![rerefernce2](https://user-images.githubusercontent.com/70904231/93606857-35491e00-f9e6-11ea-80a4-55677798a0a5.PNG)

**Comment by fooman** [comment]
@NandiniJivainfotech123 Thanks for checking. As this still reproduces for me I wonder what differences there may be.

I did note in your output the Experimental Warning which I don't get. So I tested with various node versions
v14.12.0
v12.13.1
v10.18.1
on Macos and they all produce the same error.

```
❯ ./node_modules/webpack-cli/bin/cli.js --no-progress --env.mode development
Emitting no ServiceWorker in development mode.
/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/@magento/pwa-buildpack/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:219
                  throw createError(
                  ^

Error: [React Refresh] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.
    at createError (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/@magento/pwa-buildpack/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/utils/createError.js:7:10)
    at compilation.hooks.normalModuleLoader.tap (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/@magento/pwa-buildpack/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:219:25)
    at SyncHook.eval [as call] (eval at create (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
    at SyncHook.lazyCompileHook (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/tapable/lib/Hook.js:154:20)
    at NormalModule.createLoaderContext (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/NormalModule.js:233:40)
    at NormalModule.doBuild (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/NormalModule.js:285:30)
    at NormalModule.build (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/NormalModule.js:438:15)
    at Compilation.buildModule (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/Compilation.js:702:10)
    at factory.create (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/Compilation.js:949:14)
    at factory (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
    at hooks.afterResolve.callAsync (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/tapable/lib/Hook.js:154:20)
    at resolver (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
    at process.nextTick (/Users/kristof/Projects/__OpenSource-Contributions/pwa-temp/scaffold-test-1/node_modules/webpack/lib/NormalModuleFactory.js:346:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Really not sure what other info I can provide at this stage.

**Comment by papiliond** [comment]
I think the ReactRefreshWebpackPlugin should only be included when running the web server. In case I want to make a development build with `webpack --no-progress --env.mode development`, I don't necessary want to hot reload.

**Comment by sirugh** [comment]
Using the release candidate, `v9.0.0-rc1`, I saw no errors from this :/

I installed with `yarn` and ran `yarn build:dev` and `yarn build:prod` which both run `webpack` and saw no errors. 

```
"build:dev": "yarn run clean && yarn run validate-queries && webpack --no-progress --env.mode development",
"build:prod": "yarn run clean && webpack --no-progress --env.mode production",
```

I also ran `./node_modules/webpack-cli/bin/cli.js --no-progress --env.mode development` and it built without error. I'm not sure what to say except that this appears to be working on the release client. Would you please try the commands using `v9.0.0-rc1` and let me know if it works?

**Comment by sirugh** [comment]
Ok, FWIW I see that we have actually added the suggested lines to the plugins: https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/WebpackTools/PWADevServer.js#L191-L197

Note that the code in question was moved from `getClientConfig` to `PWADevServer`.

I'll close this for now as it seems to be working and the suggested fix seems to have snuck its way into the repo :)
