### ISSUE TITLE
[bug]: Can´t install PWA Studio: ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by tim-breitenstein-it** [magento/pwa-studio#3126]
**Describe the bug**

Can´t install PWA Studio

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test@0.0.1
npm ERR! Found: eslint-plugin-react-hooks@2.0.1
npm ERR! node_modules/eslint-plugin-react-hooks
npm ERR!   dev eslint-plugin-react-hooks@"~2.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-react-hooks@"^1.6.0" from @magento/eslint-config@1.5.2
npm ERR! node_modules/@magento/eslint-config
npm ERR!   dev @magento/eslint-config@"~1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**To reproduce**

1. Run: `npx @magento/create-pwa`
2. Configuration:
```
@magento/create-pwa v1.3.0
Creating a PWA Studio project
? Project root directory (will be created if it does not exist) test
? Short name of the project to put in the package.json "name" field test
? Name of the author to put in the package.json "author" field IT-Breitenstein.Tim <tim@breitenstein.it>
? Which template would you like to use to bootstrap test? Defaults to "@magento/venia-concept". @magento/venia-concept
? Magento instance to use as a backend (will be added to `.env` file) 2.4-develop
? Braintree API token to use to communicate with your Braintree instance (will be added to `.env` file) *************************************
? NPM package management client to use npm
? Install package dependencies with npm after creating project Yes

Running command:

buildpack create-project test --name "test" --author "IT-Breitenstein.Tim <tim@breitenstein.it>" --template "@magento/venia-concept" --backend-url "https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "*************************************" --npm-client "npm"

```
3. See error:
```
  ℹ  Finding @magento/venia-concept tarball on NPM
  ℹ  Downloading and unpacking https://registry.npmjs.org/@magento/venia-concept/-/venia-concept-10.0.0.tgz
  ℹ  Unpacked @magento/venia-concept
  ℹ  Creating a new PWA project 'test' in test
  ℹ  Successfully wrote a fresh configuration file to /var/www/tim/test/.env
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test@0.0.1
npm ERR! Found: eslint-plugin-react-hooks@2.0.1
npm ERR! node_modules/eslint-plugin-react-hooks
npm ERR!   dev eslint-plugin-react-hooks@"~2.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-react-hooks@"^1.6.0" from @magento/eslint-config@1.5.2
npm ERR! node_modules/@magento/eslint-config
npm ERR!   dev @magento/eslint-config@"~1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/tim/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tim/.npm/_logs/2021-04-16T09_13_43_455Z-debug.log
  ⓧ  Error: Command failed: /bin/sh -c npm install
App creation cancelled.
```

**Expected behavior**

Fresh Magento 2 PWA studio installation

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
1 info using npm@7.6.2
2 info using node@v14.15.4
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/var/www/tim/test/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/tim/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 7e2e3d8ba0a955f8
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 0ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 16ms
24 timing idealTree:userRequests Completed in 0ms
25 silly idealTree buildDeps
26 silly fetch manifest sharp@~0.23.3
27 http fetch GET 304 https://registry.npmjs.org/sharp 218ms (from cache)
28 silly fetch manifest @adobe/apollo-link-mutation-queue@~1.0.2
29 http fetch GET 304 https://registry.npmjs.org/@adobe%2fapollo-link-mutation-queue 1558ms (from cache)
30 silly fetch manifest @apollo/client@~3.1.2
31 http fetch GET 304 https://registry.npmjs.org/@apollo%2fclient 74ms (from cache)
32 silly fetch manifest graphql@~15.3.0
33 http fetch GET 304 https://registry.npmjs.org/graphql 50ms (from cache)
34 silly fetch manifest react@~17.0.1
35 http fetch GET 304 https://registry.npmjs.org/react 48ms (from cache)
36 silly fetch manifest react@^16.8.0
37 silly fetch manifest subscriptions-transport-ws@^0.9.0
38 http fetch GET 304 https://registry.npmjs.org/subscriptions-transport-ws 53ms (from cache)
39 silly fetch manifest @babel/core@~7.3.4
40 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 59ms (from cache)
41 silly fetch manifest @babel/plugin-proposal-class-properties@~7.3.4
42 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-class-properties 60ms (from cache)
43 silly fetch manifest @babel/plugin-proposal-object-rest-spread@~7.3.4
44 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-object-rest-spread 66ms (from cache)
45 silly fetch manifest @babel/plugin-syntax-dynamic-import@~7.2.0
46 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-syntax-dynamic-import 50ms (from cache)
47 silly fetch manifest @babel/plugin-syntax-jsx@~7.2.0
48 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-syntax-jsx 56ms (from cache)
49 silly fetch manifest @babel/plugin-transform-react-jsx@~7.3.0
50 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-transform-react-jsx 76ms (from cache)
51 silly fetch manifest @babel/plugin-transform-runtime@~7.4.4
52 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-transform-runtime 86ms (from cache)
53 silly fetch manifest @babel/preset-env@~7.3.4
54 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-env 80ms (from cache)
55 silly fetch manifest @babel/runtime@~7.4.2
56 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 73ms (from cache)
57 silly fetch manifest @magento/babel-preset-peregrine@~1.1.0
58 http fetch GET 304 https://registry.npmjs.org/@magento%2fbabel-preset-peregrine 1805ms (from cache)
59 silly fetch manifest babel-plugin-dynamic-import-node@~2.2.0
60 http fetch GET 304 https://registry.npmjs.org/babel-plugin-dynamic-import-node 254ms (from cache)
61 silly fetch manifest babel-plugin-graphql-tag@~2.0.0
62 http fetch GET 304 https://registry.npmjs.org/babel-plugin-graphql-tag 939ms (from cache)
63 silly fetch manifest graphql-tag@^2.10.1
64 http fetch GET 304 https://registry.npmjs.org/graphql-tag 213ms (from cache)
65 silly fetch manifest react-refresh@0.8.3
66 http fetch GET 304 https://registry.npmjs.org/react-refresh 220ms (from cache)
67 silly fetch manifest @magento/eslint-config@~1.5.0
68 http fetch GET 304 https://registry.npmjs.org/@magento%2feslint-config 2000ms (from cache)
69 silly fetch manifest eslint-config-prettier@^6.0.0
70 http fetch GET 304 https://registry.npmjs.org/eslint-config-prettier 229ms (from cache)
71 silly fetch manifest eslint@~5.14.1
72 http fetch GET 304 https://registry.npmjs.org/eslint 274ms (from cache)
73 silly fetch manifest eslint-plugin-jsx-a11y@~6.2.1
74 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-jsx-a11y 57ms (from cache)
75 silly fetch manifest eslint-plugin-package-json@~0.1.3
76 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-package-json 894ms (from cache)
77 silly fetch manifest eslint-plugin-react@~7.21.5
78 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-react 55ms (from cache)
79 silly fetch manifest eslint-plugin-react-hooks@~2.0.1
80 http fetch GET 304 https://registry.npmjs.org/eslint-plugin-react-hooks 294ms (from cache)
81 silly fetch manifest eslint-plugin-react-hooks@^1.6.0
82 timing idealTree Completed in 9993ms
83 timing command:install Completed in 9996ms
84 verbose stack Error: unable to resolve dependency tree
84 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1143:25)
84 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1120:34)
84 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:838:11)
84 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
84 verbose stack     at async Promise.all (index 1)
84 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
84 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:120:5)
85 verbose cwd /var/www/tim/test
86 verbose Linux 5.4.0-70-generic
87 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
88 verbose node v14.15.4
89 verbose npm  v7.6.2
90 error code ERESOLVE
91 error ERESOLVE unable to resolve dependency tree
92 error
93 error While resolving: ^[[1mpwa-radhalle-com^[[22m@^[[1m0.0.1^[[22m
93 error Found: ^[[1meslint-plugin-react-hooks^[[22m@^[[1m2.0.1^[[22m^[[2m^[[22m
93 error ^[[2mnode_modules/eslint-plugin-react-hooks^[[22m
93 error   ^[[33mdev^[[39m ^[[1meslint-plugin-react-hooks^[[22m@"^[[1m~2.0.1^[[22m" from the root project
93 error
93 error Could not resolve dependency:
93 error ^[[35mpeer^[[39m ^[[1meslint-plugin-react-hooks^[[22m@"^[[1m^1.6.0^[[22m" from ^[[1m@magento/eslint-config^[[22m@^[[1m1.5.2^[[22m^[[2m^[[22m
93 error ^[[2mnode_modules/@magento/eslint-config^[[22m
93 error   ^[[33mdev^[[39m ^[[1m@magento/eslint-config^[[22m@"^[[1m~1.5.0^[[22m" from the root project
93 error
93 error Fix the upstream dependency conflict, or retry
93 error this command with --force, or --legacy-peer-deps
93 error to accept an incorrect (and potentially broken) dependency resolution.
93 error
93 error See /home/tim/.npm/eresolve-report.txt for a full report.
94 verbose exit 1
```

**Please complete the following device information:**

```
uname -a
Linux magento-2-test 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
npm -v
7.6.2
```
```
node -v
v14.15.42
```

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [x] `create-pwa`

**Comment by evan-burrell** [comment]
@tim-breitenstein-it It looks like you are using NPM 7, this happens when there is a peer dependency mismatch, you should be able to install by using `npm install --legacy-peer-deps`
