### ISSUE TITLE
[bug]: Faild to build under FreeBSD

### ISSUE THREAD

**Issue by iron-udjin** [magento/pwa-studio#3583]
**Describe the bug**

I'm trying to build v12.1.0 under FreeBSD 13

**To reproduce**

1. fetch https://github.com/magento/pwa-studio/archive/refs/tags/v12.1.0.tar.gz
2. tar xf v12.1.0.tar.gz
3. cd pwa-studio-12.1.0
4. yarn

**Result:**

```
[5/5] Building fresh packages...
$ node scripts/monorepo-introduction.js
Preparing packages...
Ensuring valid environment...
/tmp/pwa-studio-12.1.0/node_modules/application-config-path/index.js:35
  throw new Error('Platform not supported')
  ^

Error: Platform not supported
    at applicationConfigPath (/tmp/pwa-studio-12.1.0/node_modules/application-config-path/index.js:35:9)
    at Object.<anonymous> (/tmp/pwa-studio-12.1.0/node_modules/devcert/dist/constants.js:18:21)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/pwa-studio-12.1.0/node_modules/devcert/dist/index.js:8:21)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)

Node.js v17.0.1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. You could try a different version of Node: v12 or v14. If issue still occurs with these versions, please reopen as a Bug.
