### ISSUE TITLE
[bug]: 2.4-develop URL Auto-generated by create-pwa doesn't work

### ISSUE THREAD

**Issue by schizek** [magento/pwa-studio#4009]
**Describe the bug**

After selecting `2.4-develop` for the question "Magento instance to use as a backend (will be added to `.env` file)" it appears the url generated doesn't work.  If I manually update the `.env` file to use https://venia.magento.com it runs as expected.

**To reproduce**

1. Run create-pwa
    ```
    ❯ npx @magento/create-pwa
    @magento/create-pwa v2.3.3
    Creating a PWA Studio project
    ? Project root directory (will be created if it does not exist) testing2
    ? Short name of the project to put in the package.json "name" field testing2
    ? Name of the author to put in the package.json "author" field Someone <someone@example.com>
    ? Which template would you like to use to bootstrap testing2? Defaults to "@magento/venia-concept". @magento/venia-concept
    ? Magento instance to use as a backend (will be added to `.env` file) 2.4-develop
    ? Edition of the magento store (Adobe Commerce or Magento Open Source) AC
    ? Braintree API token to use to communicate with your Braintree instance (will be added to `.env` file) sandbox_8yrzsvtm_s2bg8fs563crhqzk
    ? NPM package management client to use npm
    ? Install package dependencies with npm after creating project Yes

    Running command:

    buildpack create-project testing2 --name "testing2" --author "Someone <someone@example.com>" --template "@magento/venia-concept" --backend-url "https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --backend-edition "AC" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "npm"


      ℹ  Found @magento/venia-concept template in cache
      ℹ  Creating a new PWA project 'testing2' in testing2
      ℹ  Successfully wrote a fresh configuration file to /Users/stephanieglaser/Sites/pwa-studio/testing2/.env
    npm WARN ERESOLVE overriding peer dependency
    npm WARN ERESOLVE overriding peer dependency
    npm WARN ERESOLVE overriding peer dependency
    npm WARN ERESOLVE overriding peer dependency
    npm WARN ERESOLVE overriding peer dependency
    npm WARN ERESOLVE overriding peer dependency
    npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
    npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
    npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
    npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
    npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
    npm WARN deprecated mini-create-react-context@0.4.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
    npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
    npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
    npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
    npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
    npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
    npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm WARN deprecated devcert@1.1.3: critical regex denial of service bug fixed in 1.2.1 patch
    npm WARN deprecated subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md

    added 2545 packages, and audited 2546 packages in 59s

    248 packages are looking for funding
      run `npm fund` for details

    64 vulnerabilities (14 moderate, 36 high, 14 critical)

    To address all issues possible (including breaking changes), run:
      npm audit fix --force

    Some issues need review, and may require choosing
    a different dependency.

    Run `npm audit` for details.
      ✔  Installed dependencies for 'testing2' project
      ⚠  Created new PWA project testing2. Next steps:

        - cd testing2 before running the below commands.

        - npm run buildpack -- create-custom-origin . to generate a unique, secure custom domain for your new project. Highly recommended.

        - npm run watch to start the dev server and do real-time development.

        - npm run storybook to start Storybook dev server and view available components in your app.

        - npm run build to build the project into optimized assets in the '/dist' directory.

        - npm start after build to preview the app on a local staging server.
    ```
2. Change to the new directory created
    ```
    ❯ cd testing2
    ```
3. Run buildback
    ```
    ❯ npm run buildpack -- create-custom-origin .

    > testing2@0.0.1 buildpack
    > buildpack create-custom-origin .

    Creating a local development domain requires temporary administrative privileges.
    Please enter the password for myuser on mycomputer.local.
    Password:
      ℹ  Acquired custom hostname and SSL cert for testing2-gendj.local.pwadev. Development server will run on port 8060 and staging server will run on port
        9060.
    ```
4. Run watch
    ```
    ❯ npm run watch

    > testing2@0.0.1 watch
    > webpack-dev-server --progress --color --env.mode development

    FetchError: invalid json response body at https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/graphql reason: Unexpected token A in JSON at position 0
        at /Users/myuser/Sites/pwa-studio/testing2/node_modules/@magento/pwa-buildpack/node_modules/node-fetch/lib/index.js:273:32
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async module.exports (/Users/myuser/Sites/pwa-studio/testing2/webpack.config.js:62:29) {
      type: 'invalid-json'
    }
    FetchError: invalid json response body at https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/graphql reason: Unexpected token A in JSON at position 0
        at /Users/myuser/Sites/pwa-studio/testing2/node_modules/@magento/pwa-buildpack/node_modules/node-fetch/lib/index.js:273:32
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async module.exports (/Users/myuser/Sites/pwa-studio/testing2/webpack.config.js:62:29)
    ```
5. Edit the `.env` file and change...
    ```
    MAGENTO_BACKEND_URL=https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/
    ```
    to...
    ```
    MAGENTO_BACKEND_URL=https://venia.magento.com/
    ```
6. Re-run watch and note that it completes successfully.

**Expected behavior**

I expect that `nom run watch` should complete successfully

**Possible solutions**

One odd thing to note is that in the `.env` file generated it states to set a `MAGENTO_BACKEND_URL` of a Magento 2.3 instance.  This seems very odd since 2.3 is no longer supported.  The current version is 2.4.5-p1.  Below is that section from my auto-generated `.env` file after running the first step previously mentioned.

```
#### Connecting to a Magento store #############################################
#
#   Connect to an instance of Magento 2.3 by specifying its public domain name.
MAGENTO_BACKEND_URL=https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/
#
################################################################################
```

**Debug Report**

```
❯ yarn build:report
yarn run v1.22.19
$ buildpack generate-build-report
  ℹ  Generating build report for testing2@0.0.1. This may take a moment.

  ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in package-lock.json
    @magento/pwa-buildpack @ 11.4.1
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.2.2
    @magento/eslint-config @ 1.5.3
    @magento/pagebuilder @ 7.4.2
    @magento/peregrine @ 12.6.0
    @magento/pwa-theme-venia @ 1.4.0
    @magento/upward-security-headers @ 1.0.11
    @magento/venia-ui @ 9.7.0

  ℹ  Inspecting Magento Backend
    Not using sample backend.
    Backend is UP!

  ℹ  Inspecting System
    OS: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Node Version: v16.18.1
    NPM Version: 8.19.2


✨  Done in 4.38s.
```

**Please complete the following device information:**

-   Device: Mac
-   Browser: N/A - Terminal
-   Browser Version: N/A
-   Magento Version: Adobe Commerce 2.4

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [x] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Hi @schizek , please try using the latest release branch, rather than a development branch

**Comment by schizek** [comment]
@anthoula I did not specifically use any branch.  I simply ran `npx @magento/create-pwa`.  How would I verify I'm using the latest release when running that command?

**Comment by schizek** [comment]
@anthoula I opened this separate issue which might be related to the reason the URLs are not working... https://github.com/magento/pwa-studio/issues/4010
