### ISSUE TITLE
[bug]: Sign-in broken following 13.3.0

### ISSUE THREAD

**Issue by justinconabree** [magento/pwa-studio#4219]
**Describe the bug**

Login no longer works following 13.3.0. This is also visible on venia.magento.com

**To reproduce**

1. Open Sign-in dropdown in menu
2. Enter credentials
3. Try to sign in
4. Dropdown will close without doing anything else

1. Go to /sign-in page
2. Enter credentials
3. Try to sign in
4. Button will be grayed out (error in console)

**Expected behavior**

Able to login

**Screenshots**

![image](https://github.com/magento/pwa-studio/assets/68294336/e2290c48-7897-4872-b92e-02c1e45009d1)

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: 120.0.6099.71
-   Magento Version [e.g Adobe Commerce 2.4]: N/A

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by RaghavendraTirumalasetti** [comment]
The issue is reproducible only with the following steps:

- Go to /sign-in page
- Enter credentials
- Try to sign in

Not reproducible with these steps 

- Open Sign-in dropdown in menu
- Enter credentials
- Try to sign in

Hence Conforming the issue 
<img width="1206" alt="Screenshot 2023-12-19 at 7 10 47 PM" src="https://github.com/magento/pwa-studio/assets/104980124/f094d1e5-3615-4e28-8c40-1ed1ac284693">

**Comment by justinconabree** [comment]
For the dropdown, I was able to reproduce it once this morning, but all subsequent attempts now work properly. Maybe a cache issue..
That being said, the dropdown closes whether or not the sign-in was successful. So if it wasn't successful we no longer see a form error. It should only be close on successful logins

**Comment by adithmohn** [comment]
I have the same issue. Did you got any fix.

**Comment by glo82145** [comment]
https://github.com/adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
@adobe  export issue to JIRA project PWA as Bug

**Comment by RaghavendraTirumalasetti** [comment]
Issue confirmed  we are working on it

**Comment by adithmohn** [comment]
Unexpected token '<', "<!DOCTYPE "... is not valid JSON
getting this, 304 graphql error and typeerror handle trigger,

**Comment by coresh** [comment]
@magento

```
sign-in:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src http: https: https://venia.magento.com 'nonce-edTvVDSNCCxjB0hJdzpjSlB29OFuyfiT0NYR2MPM9CFH3'". Either the 'unsafe-inline' keyword, a hash ('sha256-t6eIEkK+TvQyXCqBZCtwrzgRS0tXPoL5UYqXprJkct0='), or a nonce ('nonce-...') is required to enable inline execution.

19:06:21.872 sign-in:128 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src http: https: https://venia.magento.com 'nonce-edTvVDSNCCxjB0hJdzpjSlB29OFuyfiT0NYR2MPM9CFH3'". Either the 'unsafe-inline' keyword, a hash ('sha256-v1wjZ5LfLME2Flio6I+INPBANXI1ItLVfvLRWMMPcXQ='), or a nonce ('nonce-...') is required to enable inline execution.

1819:06:21.967 Fetch finished loading: GET "<URL>".
6519:06:22.171 Fetch finished loading: GET "<URL>".
19:06:21.989 sign-in:1 [DOM] Found 2 elements with non-unique id #email: (More info: https://goo.gl/9p2vKq) <input autocomplete=​"email" class=​"textInput-input-cn- field-input-HW6 appearance-none bg-white border-2 border-solid border-input flex-textInput h-[2.5rem]​ inline-flex m-0 max-w-full rounded-input text-colorDefault w-full focus_outline-none focus_shadow-inputFocus disabled_text-subtle" id=​"email" name=​"email" value>​…​</input>​flex <input autocomplete=​"email" aria-label=​"Email Required" class=​"textInput-input-cn- field-input-HW6 appearance-none bg-white border-2 border-solid border-input flex-textInput h-[2.5rem]​ inline-flex m-0 max-w-full rounded-input text-colorDefault w-full focus_outline-none focus_shadow-inputFocus disabled_text-subtle" id=​"email" name=​"email" value>​…​</input>​flex
19:06:22.318 client.4718af5135ab4e8d1521.js:2581 Fetch finished loading: POST "https://venia.magento.com/graphql".
ze @ client.4718af5135ab4e8d1521.js:2581
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:544
Subscription @ client.4718af5135ab4e8d1521.js:602
subscribe @ client.4718af5135ab4e8d1521.js:606
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:766
Subscription @ client.4718af5135ab4e8d1521.js:602
subscribe @ client.4718af5135ab4e8d1521.js:606
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:1116
Promise.then
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:1116
Subscription @ client.4718af5135ab4e8d1521.js:602
subscribe @ client.4718af5135ab4e8d1521.js:606
(anonymous) @ client.4718af5135ab4e8d1521.js:611
Subscription @ client.4718af5135ab4e8d1521.js:602
subscribe @ client.4718af5135ab4e8d1521.js:606
RetryableOperation.try @ vendors.c41b216f4a3b78edaffa.js:1104
RetryableOperation.start @ vendors.c41b216f4a3b78edaffa.js:1104
RetryLink.request @ vendors.c41b216f4a3b78edaffa.js:1111
(anonymous) @ client.4718af5135ab4e8d1521.js:266
MutationQueueLink.processOperation @ client.4718af5135ab4e8d1521.js:2939
(anonymous) @ client.4718af5135ab4e8d1521.js:2941
Subscription @ client.4718af5135ab4e8d1521.js:2067
subscribe @ client.4718af5135ab4e8d1521.js:2069
complete @ vendors.c41b216f4a3b78edaffa.js:78
Concast.start @ vendors.c41b216f4a3b78edaffa.js:78
Concast @ vendors.c41b216f4a3b78edaffa.js:78
QueryManager.getObservableFromLink @ vendors.c41b216f4a3b78edaffa.js:213
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:163
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:163
step @ client.4718af5135ab4e8d1521.js:533
(anonymous) @ client.4718af5135ab4e8d1521.js:534
(anonymous) @ client.4718af5135ab4e8d1521.js:516
__awaiter @ client.4718af5135ab4e8d1521.js:516
QueryManager.mutate @ vendors.c41b216f4a3b78edaffa.js:160
ApolloClient.mutate @ vendors.c41b216f4a3b78edaffa.js:255
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:3228
(anonymous) @ client.4718af5135ab4e8d1521.js:1995
asyncGeneratorStep @ client.4718af5135ab4e8d1521.js:1981
_next @ client.4718af5135ab4e8d1521.js:1983
Promise.then
asyncGeneratorStep @ client.4718af5135ab4e8d1521.js:1981
_next @ client.4718af5135ab4e8d1521.js:1983
(anonymous) @ client.4718af5135ab4e8d1521.js:1983
(anonymous) @ client.4718af5135ab4e8d1521.js:1982
thunk @ client.4718af5135ab4e8d1521.js:1997
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:750
dispatch @ vendors.c41b216f4a3b78edaffa.js:513
(anonymous) @ client.4718af5135ab4e8d1521.js:2016
asyncGeneratorStep @ client.4718af5135ab4e8d1521.js:1981
_next @ client.4718af5135ab4e8d1521.js:1983
(anonymous) @ client.4718af5135ab4e8d1521.js:1983
(anonymous) @ client.4718af5135ab4e8d1521.js:1982
thunk @ client.4718af5135ab4e8d1521.js:2020
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:750
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:506
(anonymous) @ client.4718af5135ab4e8d1521.js:741
fk @ vendors.c41b216f4a3b78edaffa.js:3013
t.unstable_runWithPriority @ client.4718af5135ab4e8d1521.js:2168
gg @ vendors.c41b216f4a3b78edaffa.js:2325
Oj @ vendors.c41b216f4a3b78edaffa.js:3002
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:3001
V @ client.4718af5135ab4e8d1521.js:2156
w.port1.onmessage @ client.4718af5135ab4e8d1521.js:2136
19:07:31.487 24.b981f1ba295e9d798d57.js:62 Uncaught (in promise) TypeError: n is not a function
    at 24.b981f1ba295e9d798d57.js:62:7
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (client.4718af5135ab4e8d1521.js:1981:186)
    at _next (client.4718af5135ab4e8d1521.js:1983:19)
    at client.4718af5135ab4e8d1521.js:1983:135
    at new Promise (<anonymous>)
    at client.4718af5135ab4e8d1521.js:1982:8
    at 24.b981f1ba295e9d798d57.js:69:29
    at FormController.onSubmitHandler (vendors.c41b216f4a3b78edaffa.js:1381:160)
    at FormController.emit (client.4718af5135ab4e8d1521.js:2435:25)
(anonymous) @ 24.b981f1ba295e9d798d57.js:62
asyncGeneratorStep @ client.4718af5135ab4e8d1521.js:1981
_next @ client.4718af5135ab4e8d1521.js:1983
(anonymous) @ client.4718af5135ab4e8d1521.js:1983
(anonymous) @ client.4718af5135ab4e8d1521.js:1982
(anonymous) @ 24.b981f1ba295e9d798d57.js:69
onSubmitHandler @ vendors.c41b216f4a3b78edaffa.js:1381
emit @ client.4718af5135ab4e8d1521.js:2435
submitForm @ vendors.c41b216f4a3b78edaffa.js:1363
Rb @ vendors.c41b216f4a3b78edaffa.js:2037
Xb @ vendors.c41b216f4a3b78edaffa.js:2037
Yb @ vendors.c41b216f4a3b78edaffa.js:2185
Ze @ vendors.c41b216f4a3b78edaffa.js:2187
se @ vendors.c41b216f4a3b78edaffa.js:2194
(anonymous) @ vendors.c41b216f4a3b78edaffa.js:2282
Pe @ vendors.c41b216f4a3b78edaffa.js:3152
Nb @ vendors.c41b216f4a3b78edaffa.js:2215
jd @ vendors.c41b216f4a3b78edaffa.js:2215
yc @ vendors.c41b216f4a3b78edaffa.js:2136
hd @ vendors.c41b216f4a3b78edaffa.js:2121
t.unstable_runWithPriority @ client.4718af5135ab4e8d1521.js:2168
gg @ vendors.c41b216f4a3b78edaffa.js:2325
Hb @ vendors.c41b216f4a3b78edaffa.js:3149
gd @ vendors.c41b216f4a3b78edaffa.js:2119

```    

The test link:

[https://venia.magento.com/sign-in](https://venia.magento.com/sign-in)

IMHO: Critical issue.

Fix-Update: would be great

Thank you

![Screenshot From 2024-11-11 19-08-12](https://github.com/user-attachments/assets/7780e2c2-109f-4c58-b8e2-9578d444c345)

**Comment by coresh** [comment]
@magento


Click to "SIGN IN" button issue details:

![Screenshot From 2024-11-12 07-42-00](https://github.com/user-attachments/assets/bb419202-8a6b-4656-ad7f-196256dfe91b)

```
TypeError
handleTriggerClick is not a function
Call Stack
 eval
  node_modules/@magento/venia-ui/lib/components/SignIn/signIn.js:206:5
 FormController.onSubmitHandler
  node_modules/informed/dist/esm/index.js:4179:26
 FormController.emit
  node_modules/events/events.js:153:5
 FormController.submitForm
  node_modules/informed/dist/esm/index.js:3907:14
 HTMLUnknownElement.callCallback
  node_modules/react-dom/cjs/react-dom.development.js:3945:14
 Object.invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:3994:16
 invokeGuardedCallback
  node_modules/react-dom/cjs/react-dom.development.js:4056:31
 invokeGuardedCallbackAndCatchFirstError
  node_modules/react-dom/cjs/react-dom.development.js:4070:25
 executeDispatch
  node_modules/react-dom/cjs/react-dom.development.js:8243:3
 processDispatchQueueItemsInOrder
  node_modules/react-dom/cjs/react-dom.development.js:8275:7

```

**Comment by coresh** [comment]
https://github.com/magento

/sign-in page init details:

![Screenshot From 2024-11-12 08-17-48](https://github.com/user-attachments/assets/fe6277e1-5c37-43d6-b47d-02fd86b8979e)

```
Warning: Failed prop type: Invalid prop `disabled` of type `string` supplied to `Button`, expected `boolean`.
    at Button (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Button/button.js:38:7)
    at SignIn (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/SignIn/signIn.js:429:99)
    at div
    at div
    at SignInPage (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/SignInPage/index.js:118:103)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:487:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:689:29)
    at Suspense
    at Routes (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:1674:50)
    at div
    at main
    at Main (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:4894:5)
    at r (webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:14:7342)
    at VeniaHeadProvider (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Head/headProvider.js:7:169)
    at App (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:6142:5)
    at ErrorBoundary (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:6246:7)
    at AppContainer (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:6280:25)
    at AmRmaContextProvider (webpack-internal:///./src/@amasty/rma/src/context.js:19:5)
    at AmRewardPointsProvider (webpack-internal:///./src/@amasty/rewards-points/src/context.js:28:5)
    at ToastContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/Toasts/useToastContext.js:83:3)
    at WindowSizeContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/hooks/useWindowSize.js:61:22)
    at RootComponentsProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/context/rootComponents.js:11:5)
    at CheckoutContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/PeregrineContextProvider/peregrineContextProvider.js:44:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/index.js:481:46)
    at CartContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/context/cart.js:34:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/index.js:481:46)
    at CatalogContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/context/catalog.js:49:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/index.js:481:46)
    at UserContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/context/user.js:26:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/index.js:481:46)
    at AppContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/context/app.js:24:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/index.js:481:46)
    at EventingContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/context/eventing.js:14:5)
    at ErrorContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/context/unhandledErrors.js:15:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/index.js:481:46)
    at PeregrineContextProvider (webpack-internal:///./node_modules/@magento/peregrine/lib/PeregrineContextProvider/peregrineContextProvider.js:106:3)
    at IntlProvider (webpack-internal:///./node_modules/react-intl/lib/src/components/provider.js:589:47)
    at LocaleProvider (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:6349:60)
    at contextProvider_ContextProvider (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:6418:3)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:118:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:89:35)
    at Provider (webpack-internal:///./node_modules/react-redux/es/index.js:186:20)
    at ApolloProvider (webpack-internal:///./node_modules/@apollo/client/react/context/ApolloProvider.js:10:21)
    at Adapter (webpack-internal:///./node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js:6504:22)
overrideMethod @ hook.js:608
printWarning @ react.development.js:220
error @ react.development.js:196
checkPropTypes @ react.development.js:1935
validatePropTypes @ react.development.js:2136
createElementWithValidation @ react.development.js:2240
SignIn @ signIn.js:525
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
beginWork$1 @ react-dom.development.js:23935
performUnitOfWork @ react-dom.development.js:22771
workLoopSync @ react-dom.development.js:22702
renderRootSync @ react-dom.development.js:22665
performSyncWorkOnRoot @ react-dom.development.js:22288
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21888
dispatchAction @ react-dom.development.js:16139
onNext @ useQuery.js:136
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
eval @ ApolloClient.js:133
iterateObserversSafely @ ApolloClient.js:133
ObservableQuery.reportResult @ ApolloClient.js:699
next @ ApolloClient.js:674
eval @ ApolloClient.js:133
iterateObserversSafely @ ApolloClient.js:133
next @ ApolloClient.js:175
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
eval @ ApolloClient.js:75
Promise.then
eval @ ApolloClient.js:73
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
eval @ ApolloClient.js:133
iterateObserversSafely @ ApolloClient.js:133
next @ ApolloClient.js:175
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
RetryableOperation.onNext @ retryLink.js:62
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
next @ module.js:311
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
next @ index.js:34
notifySubscription @ module.js:133
onNotify @ module.js:177
next @ module.js:226
eval @ createHttpLink.js:336
Promise.then
eval @ createHttpLink.js:335
Subscription @ module.js:191
subscribe @ module.js:265
eval @ index.js:16
Subscription @ module.js:191
subscribe @ module.js:265
eval @ index.js:20
Promise.then
eval @ index.js:17
Subscription @ module.js:191
subscribe @ module.js:265
eval @ module.js:303
Subscription @ module.js:191
subscribe @ module.js:265
eval @ index.js:20
Promise.then
eval @ index.js:17
Subscription @ module.js:191
subscribe @ module.js:265
RetryableOperation.try @ retryLink.js:140
RetryableOperation.start @ retryLink.js:128
RetryLink.request @ retryLink.js:171
eval @ bundle.esm.js:419
MutationQueueLink.request @ MutationQueueLink.js:116
eval @ bundle.esm.js:418
eval @ bundle.esm.js:418
eval @ bundle.esm.js:418
eval @ bundle.esm.js:418
eval @ bundle.esm.js:418
eval @ bundle.esm.js:413
ApolloLink.execute @ ApolloLink.js:133
QueryManager.getObservableFromLink @ ApolloClient.js:1848
QueryManager.getResultsFromLink @ ApolloClient.js:1886
resultsFromLink @ ApolloClient.js:2051
QueryManager.fetchQueryByPolicy @ ApolloClient.js:2086
fromVariables @ ApolloClient.js:1934
QueryManager.fetchQueryObservable @ ApolloClient.js:1941
ObservableQuery.fetch @ ApolloClient.js:594
ObservableQuery.reobserve @ ApolloClient.js:671
eval @ ApolloClient.js:329
Subscription @ module.js:191
subscribe @ module.js:265
eval @ useQuery.js:122
invokePassiveEffectCreate @ react-dom.development.js:23482
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23569
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23442
performSyncWorkOnRoot @ react-dom.development.js:22264
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
Show 123 more frames
Show less
```

**Comment by coresh** [comment]
v14.1.0 : the issue still exists.

@RaghavendraTirumalasetti 

Fix: would be great

[https://venia.magento.com/singn-in](https://venia.magento.com/singn-in)

Thank you

**Comment by coresh** [comment]
Related [PR-4351](https://github.com/magento/pwa-studio/pull/4351)
